GET  https://dry-chamber-85395.herokuapp.com/flower

###
POST  https://dry-chamber-85395.herokuapp.com/flower
Content-Type: application/json

{
  "sepalLength": 100,
  "color": "blue",
  "price": 100
}